shopping_cart_homepage:
    path:     /
    defaults: { _controller: ShoppingCartBundle:Default:index }
shopping_cart_show:
    path:     /show
    defaults: { _controller: ShoppingCartBundle:ShoppingCart:affich }
shopping_cart_add:
    path:     /add
    defaults: { _controller: ShoppingCartBundle:ShoppingCart:add }
order_show:
    path:     /order
    defaults: { _controller: ShoppingCartBundle:Order:trah }
bill_show:
    path:     /bill
    defaults: { _controller: ShoppingCartBundle:Bill:afficher }
bill_add:
    path:     /addbill
    defaults: { _controller: ShoppingCartBundle:Bill:add }
add1:
    path:     /add1
    defaults: { _controller: ShoppingCartBundle:ShoppingCart:create}
show2:
    path:     /show2
    defaults: { _controller: ShoppingCartBundle:ShoppingCart:Affich2}
delete:
    path:     /delete/{id}
    defaults: { _controller: ShoppingCartBundle:ShoppingCart:delete}
ajouter_order:
    path:     /ajout
    defaults: { _controller: ShoppingCartBundle:Order:ajouter}

add_order:
    path:     /add_order
    defaults: { _controller: ShoppingCartBundle:Order:add_order}
all:
    path:     /all
    defaults: { _controller: ShoppingCartBundle:ShoppingCart:all}
all1:
    path:     /all1
    defaults: { _controller: ShoppingCartBundle:Order:all}
all2:
    path:     /all2
    defaults: { _controller: ShoppingCartBundle:Bill:all}
new:
    path:     /new
    defaults: { _controller: ShoppingCartBundle:ShoppingCart:new}
new1:
    path:     /new1
    defaults: { _controller: ShoppingCartBundle:Order:new}
new2:
    path:     /new2
    defaults: { _controller: ShoppingCartBundle:Bill:new}
all3:
    path:     /all3
    defaults: { _controller: ShoppingCartBundle:Velovendre:all}
new3:
    path:     /new3
    defaults: { _controller: ShoppingCartBundle:Velovendre:new}




